version: '3.3'

services:
    redismod:
        image: redislabs/redismod
        command: /usr/local/etc/redis/redis.conf
        restart: always
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
            # Location of dump.rdb, containing the journeys graph.
            - ./redis_data/:/data/
        ports:
            - 6379:6379

    backend:
        depends_on:
            - redismod
        image: citibike-journeys:latest
        command: [ "--redis=redismod:6379", "--port=3000"]
        restart: always

    nginx: 
        depends_on:
            - backend
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./frontend/build:/etc/nginx/html/
        ports:
            - 80:80
            - 443:443